### ISSUE TITLE
Return code 137 with no error

### ISSUE THREAD

**Issue by HakShak** [golangci/golangci-lint#576]
For versions > 1.15.0

We've found that for large projects, RAM becomes a problem and we see return codes of `137` with no errors when running within a docker environment with only 2GB of RAM. This goes away when bumping the docker VM up to 5GB.

Not really a report, just a breadcrumb for those that might hit return code 137.

**Comment by HakShak** [comment]
Additionally RAM usage seems to be coming from `govet`

**Comment by tbrisker** [comment]
For anyone still running into this issue: Looks like upgrading golangci-lint to v1.48.0 resolves this.

**Comment by Lisenish** [comment]
@tbrisker It fixed it for me, thanks! 👍

**Comment by semmet95** [comment]
Getting this error with golangci-lint v1.49.0 :/

**Comment by yury-kozlov** [comment]
Got a similar error: 
> ERROR: failed to solve: process "/bin/sh -c golangci-lint run ./... --config=.golangci-lint.yml --timeout 30m" 
did not complete successfully: exit code: 137

The error happened as a result of some syntax error in one of our go files: `not enough arguments in call to ...`
The workaround was to run `go build` command before the `golangci-lint` in order to catch possible issues in the code and prevent linter from running at all if there's an obvious error. Otherwise, lint ate all the memory and crashed the flow.
