### ISSUE TITLE
revive's linters-settings does not work

### ISSUE THREAD

**Issue by hi-rustin** [golangci/golangci-lint#2257]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

revive's linters-settings does not work

### Version of golangci-lint

<details>

```console
➜  bin git:(master) ✗ ./golangci-lint --version
golangci-lint has version 1.42.0 built from c6142e38 on 2021-08-17T11:47:22Z
```

</details>

### Configuration file

<details>

```console
linters:
  enable:
    - unconvert
    - unparam
    - revive

linters-settings:
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    error-code: -1
    warning-code: -1
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code

```

</details>

### Go environment

<details>

```console
➜  bin git:(master) ✗ go version                     
go version go1.16.5 darwin/amd64
```

</details>

### Verbose output of running

<details>

```console
➜  ticdc git:(master) ✗ make check-static 
tools/bin/golangci-lint run -v --timeout 10m0s --skip-files kv_gen
INFO [config_reader] Config search paths: [./ /Users/rustin/GolandProjects/ticdc /Users/rustin/GolandProjects /Users/rustin /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 13 linters: [deadcode errcheck gosimple govet ineffassign revive staticcheck structcheck typecheck unconvert unparam unused varcheck] 
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|name|types_sizes|exports_file|files|imports) took 1.668019578s 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 26.446467ms 
INFO [linters context/goanalysis] analyzers took 2m49.119898078s with top 10 stages: buildir: 1m26.583668277s, buildssa: 9.121610128s, nilness: 6.317554041s, inspect: 4.709839377s, fact_deprecated: 3.9414098s, fact_purity: 3.868821089s, typedness: 3.675765996s, ctrlflow: 3.335446431s, printf: 3.110042363s, the_only_name: 2.660762082s 
INFO [runner] Issues before processing: 362, after processing: 0 
INFO [runner] Processors filtering stat (out/in): skip_files: 355/362, path_prettifier: 362/362, autogenerated_exclude: 194/355, cgo: 362/362, exclude-rules: 63/194, nolint: 0/63, filename_unadjuster: 362/362, skip_dirs: 355/355, identifier_marker: 194/194, exclude: 194/194 
INFO [runner] processing took 41.66691ms with stages: nolint: 32.029026ms, exclude-rules: 2.720387ms, identifier_marker: 2.245896ms, autogenerated_exclude: 2.148594ms, path_prettifier: 2.063659ms, skip_dirs: 373.853µs, skip_files: 37.77µs, cgo: 25.834µs, filename_unadjuster: 18.324µs, max_same_issues: 842ns, uniq_by_line: 624ns, max_from_linter: 368ns, diff: 338ns, exclude: 245ns, source_code: 232ns, path_shortener: 211ns, severity-rules: 207ns, max_per_file_from_linter: 200ns, sort_results: 183ns, path_prefixer: 117ns 
INFO [runner] linters took 20.269815343s with stages: goanalysis_metalinter: 20.22805815s 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 220 samples, avg is 1523.0MB, max is 2164.8MB 
INFO Execution took 21.97631418s  
```

</details>

### Code example or link to a public repository

<details>

https://github.com/pingcap/ticdc/blob/e87252008ccaa6ae40c7585ccadd3285c9d8d363/Makefile#L196

</details>

**Comment by hi-rustin** [comment]
Also, I found that 1.37.0 does not have this issue.

**Comment by butuzov** [comment]
1. 0.8 conf is pretty high. 
2. Before @ldez added revive configuration, it was working with defaults (not all rules + default values).
3. You can check demo config for revive against its testdata here https://github.com/butuzov/todayilearned/tree/v2/sandbox-go/linters

**Comment by butuzov** [comment]
Works perfectly on your repo with confidience `0.1`. Confidince isn't something related to a.i., sometimes its just hardcoded values for specific revive's rules.

**Comment by hi-rustin** [comment]
> Works perfectly on your repo with confidence `0.1`. Confidence isn't something related to a.i., sometimes its just hardcoded values for specific revive's rules.

Thanks for your help!  💚 💙 💜 💛 ❤️


```log
 ticdc git:(master) ✗ make check-static          
tools/bin/golangci-lint run --timeout 10m0s --skip-files kv_gen
WARN [runner/nolint] Found unknown linters in //nolint directives: exported 
tests/bank/case.go:415:2: modifies-parameter: parameter 'ctx' seems to be modified (revive)
        ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
        ^
tests/bank/case.go:428:2: modifies-parameter: parameter 'ctx' seems to be modified (revive)
        ctx, cancel := context.WithTimeout(ctx, 30*time.Minute)
        ^
integration/framework/dsl.go:114:50: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
                        return &errorCheckableAndAwaitable{errors.New("Maximum retry interval reached")}
                                                                      ^
integration/framework/sql_helper.go:415:21: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
                return errors.New("Check: nil result")
                                  ^
integration/framework/sql_helper.go:421:20: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
        return errors.New("Check failed")
                          ^
pkg/errors/helper.go:58:2: modifies-parameter: parameter 'err' seems to be modified (revive)
        err = errors.Cause(err)
        ^
pkg/workerpool/pool_impl.go:62:8: modifies-parameter: parameter 'ctx' seems to be modified (revive)
        errg, ctx := errgroup.WithContext(ctx)
              ^
pkg/logutil/log.go:155:2: modifies-parameter: parameter 'p' seems to be modified (revive)
        p = bytes.TrimSpace(p)
        ^
pkg/logutil/log.go:190:3: modifies-parameter: parameter 'level' seems to be modified (revive)
                level = zapcore.ErrorLevel
                ^
pkg/cyclic/mark/mark.go:91:4: modifies-parameter: parameter 'upstreamDSN' seems to be modified (revive)
                        upstreamDSN += ("&tls=" + tlsName)
                        ^
pkg/cyclic/mark/mark.go:93:4: modifies-parameter: parameter 'upstreamDSN' seems to be modified (revive)
                        upstreamDSN += ("?tls=" + tlsName)
                        ^
cdc/puller/frontier/frontier.go:71:2: modifies-parameter: parameter 'span' seems to be modified (revive)
        span = span.Hack()
        ^
cdc/puller/frontier/heap.go:153:3: modifies-parameter: parameter 'x' seems to be modified (revive)
                x = p
                ^
pkg/etcd/etcdkey.go:89:2: modifies-parameter: parameter 'key' seems to be modified (revive)
        key = key[len(EtcdKeyBase):]
        ^
pkg/etcd/etcdkey.go:95:3: modifies-parameter: parameter 'key' seems to be modified (revive)
                key = key[len(ownerKey):]
                ^
pkg/etcd/etcdkey.go:97:4: modifies-parameter: parameter 'key' seems to be modified (revive)
                        key = key[1:]
                        ^
cdc/sink/codec/craft/decoder.go:111:2: modifies-parameter: parameter 'bits' seems to be modified (revive)
        bits, x, err := decodeUvarint32(bits)
        ^
cdc/sink/codec/craft/decoder.go:116:2: modifies-parameter: parameter 'bits' seems to be modified (revive)
        bits, x, err := decodeVarint32(bits)
        ^
cdc/sink/codec/craft/decoder.go:140:2: modifies-parameter: parameter 'bits' seems to be modified (revive)
        bits, bytes, err := decodeBytes(bits)
        ^
cdc/sink/codec/craft/encoder.go:54:3: modifies-parameter: parameter 'data' seems to be modified (revive)
                data >>= 7
                ^
cdc/sink/codec/craft/encoder.go:66:3: modifies-parameter: parameter 'data' seems to be modified (revive)
                data >>= 7
                ^
pkg/version/check.go:71:2: modifies-parameter: parameter 'v' seems to be modified (revive)
        v = versionHash.ReplaceAllLiteralString(v, "")
        ^
pkg/version/check.go:72:2: modifies-parameter: parameter 'v' seems to be modified (revive)
        v = strings.TrimSuffix(v, "-dirty")
        ^
cdc/sink/producer/pulsar/option.go:173:2: modifies-parameter: parameter 'prefix' seems to be modified (revive)
        prefix = prefix + "."
        ^
pkg/orchestrator/etcd_worker.go:280:3: modifies-parameter: parameter 'patchGroups' seems to be modified (revive)
                patchGroups = patchGroups[1:]
                ^
pkg/orchestrator/reactor_state_tester.go:33:3: modifies-parameter: parameter 'initKVEntries' seems to be modified (revive)
                initKVEntries = make(map[string]string)
                ^
pkg/util/overlap_merge_test.go:122:5: modifies-parameter: parameter 'c' seems to be modified (revive)
                                c = append(c, Range{
                                ^
tests/dailytest/data.go:86:10: modifies-parameter: parameter 'n' seems to be modified (revive)
        for ; ; n-- {
                ^
tests/dailytest/db.go:34:3: modifies-parameter: parameter 'min' seems to be modified (revive)
                min, err = strconv.ParseInt(column.min, 10, 64)
                ^
tests/dailytest/db.go:40:4: modifies-parameter: parameter 'max' seems to be modified (revive)
                        max, err = strconv.ParseInt(column.max, 10, 64)
                        ^
tests/dailytest/rand.go:73:3: modifies-parameter: parameter 'min' seems to be modified (revive)
                min := randInt(0, 59)
                ^
tests/dailytest/rand.go:91:3: modifies-parameter: parameter 'min' seems to be modified (revive)
                min := randInt(0, 59)
                ^
tests/dailytest/db.go:62:7: modifies-parameter: parameter 'max' seems to be modified (revive)
        min, max := intRangeValue(column, 0, max)
             ^
cdc/kv/region_worker.go:70:3: modifies-parameter: parameter 'bucket' seems to be modified (revive)
                bucket = runtime.NumCPU()
                ^
cdc/kv/region_worker.go:72:4: modifies-parameter: parameter 'bucket' seems to be modified (revive)
                        bucket = maxRegionStateBucket
                        ^
cdc/kv/region_worker.go:75:4: modifies-parameter: parameter 'bucket' seems to be modified (revive)
                        bucket = minRegionStateBucket
                        ^
pkg/context/context.go:174:5: modifies-parameter: parameter 'err' seems to be modified (revive)
        if err := ctx.f(err); err != nil {
           ^
cdc/entry/codec.go:125:2: modifies-parameter: parameter 'ek' seems to be modified (revive)
        ek = ek[metaPrefixLen:]
        ^
cdc/entry/mounter.go:83:3: modifies-parameter: parameter 'workerNum' seems to be modified (revive)
                workerNum = defaultMounterWorkerNum
                ^
cdc/entry/codec.go:126:2: modifies-parameter: parameter 'ek' seems to be modified (revive)
        ek, rawKey, err := codec.DecodeBytes(ek, nil)
        ^
cdc/entry/codec.go:132:2: modifies-parameter: parameter 'ek' seems to be modified (revive)
        ek, rawTp, err := codec.DecodeUint(ek)
        ^
cdc/entry/codec.go:191:3: modifies-parameter: parameter 'b' seems to be modified (revive)
                b = b[1:]
                ^
cdc/entry/codec.go:197:9: modifies-parameter: parameter 'b' seems to be modified (revive)
                data, b, err = codec.CutOne(b)
                      ^
cdc/entry/codec.go:208:9: modifies-parameter: parameter 'b' seems to be modified (revive)
                data, b, err = codec.CutOne(b)
                      ^
cdc/puller/sorter/serde.go:25:2: modifies-parameter: parameter 'bytes' seems to be modified (revive)
        bytes = bytes[:0]
        ^
cdc/puller/sorter/unified_sorter.go:100:4: modifies-parameter: parameter 'dir' seems to be modified (revive)
                        dir = sorterConfig.SortDir
                        ^
cdc/puller/sorter/serde.go:34:2: modifies-parameter: parameter 'bytes' seems to be modified (revive)
        bytes, err := event.RawKV.UnmarshalMsg(bytes)
        ^
cdc/sink/codec/schema_registry.go:78:2: modifies-parameter: parameter 'registryURL' seems to be modified (revive)
        registryURL = strings.TrimRight(registryURL, "/")
        ^
cdc/processor/pipeline/sink.go:128:3: modifies-parameter: parameter 'resolvedTs' seems to be modified (revive)
                resolvedTs = n.barrierTs
                ^
cdc/processor/pipeline/sink.go:131:3: modifies-parameter: parameter 'resolvedTs' seems to be modified (revive)
                resolvedTs = n.targetTs
                ^
make: *** [check-static] Error 1
```

This warning seems a bit strange, since exported should be a valid linter.

**Comment by butuzov** [comment]
'Exported' is revive's rule not a linter. Nolint is taking linter names (added to golangci lint) as argument.
